### ISSUE TITLE
How to use the puck lib (and other guides using nordic pucks)

### ISSUE THREAD

**Issue by cristeahub** [bftj/bftj.github.io#14]
A guide on how to setup a locatin puck.

If necessary more guides with other pucks

**Comment by stianjensen** [comment]
http://developer.mbed.org/teams/Nordic-Pucks/code/Puck/docs/e41c83f1430e/classPuck.html

**Comment by cristeahub** [comment]
See the `import a library` guide, as that one has a lot of information that might overlap with this one
