### ISSUE TITLE
Be able to register team on bftj.co

### ISSUE THREAD

**Issue by cristeahub** [bftj/bftj.github.io#2]
So they can use 30 mins on a team name

**Comment by sigvef** [comment]
What is this?

**Comment by cristeahub** [comment]
This is a reference to our discussion about teams should be able to register a team and have some sort of high score or a score of what tasks each team has completed.

**Comment by sigvef** [comment]
Ok, I don't think I was present for that discussion. Are we implementing this?

**Comment by cristeahub** [comment]
This was talked about at 9muser very briefly, I think we thought it was a bad idea cause it'll take too long time and give too little back

**Comment by sigvef** [comment]
Ok, so I'll close this issue then.
