### ISSUE TITLE
Writing your first program

### ISSUE THREAD

**Issue by stianjensen** [bftj/bftj.github.io#42]
Something like this, perhaps? http://nordicsemiconductor.github.io/puck/tutorials/location.html

This is a link to a 'first program' guide from the end of the 'First-time setup' guide

**Comment by sigvef** [comment]
Covered by the "importing" guide and the "using the puck lib" guide?

**Comment by cristeahub** [comment]
Yes I think so. Should we link to those somewhere? Also some cross linking might be good

**Comment by stianjensen** [comment]
I'd say this is covered
