### ISSUE TITLE
Bring your DMPro t-shirt!

### ISSUE THREAD

**Issue by cristeahub** [bftj/bftj.github.io#66]
We should also say that it's an awesome subject people should take! Seems like a way to get people interested in embedded/hardware programming. I also heard the professors say that they were a bit worried people would stop taking the course

**Comment by stianjensen** [comment]
![Not gonna happen](http://media2.giphy.com/media/Mxqa0JXOjHoAg/200_s.gif)

Edit: the bringing of the t-shirt part. Mentioning the subject is cool

**Comment by aleksanb** [comment]
AND DONT TRY OPENIN DIS BRUH
