### ISSUE TITLE
Find a way to give ble devices a name

### ISSUE THREAD

**Issue by stianjensen** [bftj/bftj.github.io#84]
Navigating bluetooth apps on the phone by name when every mbed is called 'nRF5x' can get tough.

**Comment by sigvef** [comment]
probably this:

![image](https://cloud.githubusercontent.com/assets/578029/6470837/bfadd722-c1e6-11e4-9187-ff46ff1d5124.png)

https://developer.mbed.org/teams/Bluetooth-Low-Energy/code/BLE_API/docs/ecbc3405c66e/classBLEDevice.html#af7cba186092bb9328bea551d0c236c2d

**Comment by sigvef** [comment]
fixed in the puck lib.
